lista = ["Pera", "Manzana", "Melocoton", "Piña"]
print(lista)
print("La longitud de la lista es: ", len(lista))
lista.append("Uvas")
print(lista)
print ("La longitud de la lista es: ", len(lista))
fruta1=input("Añade otra fruta:")
fruta2=input("Añade una fruta más:")
lista.append(fruta1)
lista.append(fruta2)
print(lista)
print("La longitud de la lista ahora es de: ", len(lista))
lista.remove(lista[1])
print(lista)
print("La longitud de la lista ahora es de: ", len(lista))
eliminar=input("Que numero de la lista quitamos?")
lista.remove(lista[int(eliminar)])
print(lista)
print("La longitud de la lista ahora es de: ", len(lista))

